### ISSUE TITLE
`madonctl account following --all` corrupts some results

### ISSUE THREAD

**Issue by weeble** [McKael/madon#15]
When I use `--all` like so:

```
madonctl account following --all
```

and look at the results, I see multiple different accounts that all have "Moved to account ID:" pointing to the same account, and only the first is correct.

I think to observe this you'd need to be following more than 80 accounts and for some of them in the middle of the list to be marked as "moved".

It appears that when retrieving more than two pages of paginated results, madonctl is inadvertently re-using the same underlying array to store the accounts, and Golang's `json.Unmarshal` will _not_ zero out the `moving` pointer if the server response provides no value for `moving`.

Note that simply [truncating the slice](https://github.com/McKael/madon/blob/5ba59b7ca061abff280f97c88e934783eb931eb5/account.go#L117) doesn't remove the backing array.

I have more detail in a slightly sweary (sorry about that) [Mastodon thread](https://mastodon.scot/@nettles/112684559405573848). I also have [a minimal reduction of the underlying bug](https://go.dev/play/p/wZjIPm3cVKJ).

**Comment by McKael** [comment]
Wow, that's an unexpected behaviour indeed... :roll_eyes: 

Thanks a lot for the detailed report and the troubleshooting!

**Comment by McKael** [comment]
It should be fixed now (I have also updated `madonctl`).\
Thanks again for the report, please let me know if there is any issue.

I'll probably tag a new release of madonctl shortly.
