### ISSUE TITLE
Pleroma compatibility

### ISSUE THREAD

**Issue by cking** [McKael/madon#3]
pleroma doesnt use raw integers as IDs, meaning decoding the account id breaks rn

**Comment by dtluna** [comment]
I have this issue too, when is the fix coming?

**Comment by rjp** [comment]
This is fixed by https://github.com/McKael/madon/pull/10 but there's still an OAuth issue with *oma instances that I'm working on.

**Comment by rjp** [comment]
Fixed in #9 but pending merge

**Comment by McKael** [comment]
Thanks for the reminder, https://github.com/McKael/madon/pull/9 is now merged!
