### ISSUE TITLE
Return error information from body when status code != 200

### ISSUE THREAD

**Issue by roobre** [McKael/madon#4]
Right now, a request returns a non-accepted status code, an error is returned without parsing the body of said request, which usually contains useful information for debugging. It would be great to have it returned as a part of the error message.

I can work on a PR for this if you agree.

**Comment by McKael** [comment]
I don't know if there's a reliable way of extracting the information, but if you can do it successfully I'm fine with it, that would be useful.

**Comment by roobre** [comment]
Hm, perhaps I'm mistaken but I was thinking about just trying to unmarshal the body on an Error struct and return it if successful. Otherwise we can fall back to the current approach of just the HTTP code description.

Why do you think this is not reliable?

**Comment by McKael** [comment]
Oh, I thought you meant you'd parse the HTML response (many errors were not JSON-encoded, that's why I didn't bother...).
What you suggest makes sense, OK :)

**Comment by McKael** [comment]
Thanks :+1:
