### ISSUE TITLE
Use io.Reader instead of file path for media upload

### ISSUE THREAD

**Issue by roobre** [McKael/madon#6]
`UploadMedia` function should receive an `io.Reader` to avoid the need of creating files when info comes from another source, such as a network resource or an in-memory buffer.

https://github.com/McKael/madon/blob/9d8259932fb836003f10e2d6116e934f521cc1bf/media.go#L25

In order to avoid breaking compatibility, a new method (e.g `UploadMediaReader`) could be created, and `UploadMedia` be reworked to open a file and then pass the obtained `os.File` to the new method.

I can make a PR for this if you think it's ok.

**Comment by McKael** [comment]
That's a good point.
I think a new method would be perfectly ok (and then `UploadMedia` should probably call `UploadMediaReader`, I guess).

If you can make a PR, go for it, thanks a lot!
